### Criação de arrays e a função random 

In [397]:
import numpy as np 

In [398]:
lista = [1,2,3]

In [399]:
np.array(lista)

array([1, 2, 3])

In [400]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [401]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [402]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [403]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [404]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [405]:
arr = np.zeros(3)

In [406]:
arr

array([0., 0., 0.])

In [407]:
arr = np.zeros((5,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [408]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [409]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [410]:
np.linspace(0,100, 7) # numeros igualmente espaçados em um intervalo

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [411]:
aleatorios = np.random.rand(5) # aleatoria numeros entre 0 e 1

In [412]:
aleatorios

array([0.92369648, 0.43590648, 0.25773206, 0.26815421, 0.83871853])

In [413]:
aleatorios * 100 # para aumentar o intervalo de aleatoriazacao

array([92.36964784, 43.59064831, 25.77320572, 26.81542074, 83.87185277])

In [414]:
np.random.rand(5,4,3)

array([[[0.26868662, 0.28366843, 0.18998774],
        [0.60478607, 0.29688696, 0.36681048],
        [0.47604931, 0.10112742, 0.42424723],
        [0.22291943, 0.68190713, 0.13973022]],

       [[0.24687115, 0.27075014, 0.30575691],
        [0.32997264, 0.155958  , 0.94790386],
        [0.00810308, 0.1114573 , 0.03626278],
        [0.59769539, 0.25160375, 0.74872629]],

       [[0.0536922 , 0.43193547, 0.03589123],
        [0.70910579, 0.11218313, 0.00817915],
        [0.25668859, 0.79549192, 0.98726964],
        [0.84110477, 0.48104941, 0.43933014]],

       [[0.60691696, 0.55698122, 0.79355794],
        [0.70087167, 0.399783  , 0.24869227],
        [0.89087326, 0.87121679, 0.63327753],
        [0.52469556, 0.48850962, 0.29788735]],

       [[0.83626815, 0.52763714, 0.01717409],
        [0.42031584, 0.98376783, 0.28289751],
        [0.7890889 , 0.49900564, 0.32423712],
        [0.67040581, 0.966108  , 0.96286667]]])

In [415]:
np.random.randn(4) # distribuição normal

array([-1.45074576, -0.72628563, -0.65577217,  1.36767374])

In [416]:
np.random.randint(0, 100, 10)


array([ 9, 20, 75, 61, 13,  0, 49, 43,  2, 66])

In [417]:
# ou
np.random.rand(10) * 100

array([48.16625314, 65.77393793, 54.64033113, 54.27314533, 87.46882484,
       76.20557717, 83.79119078, 60.90190553,  4.61065067, 87.2665925 ])

In [418]:
arr = np.random.rand(25)

In [419]:
arr = arr.reshape((5,5))
arr

array([[0.87046696, 0.80005406, 0.89660527, 0.42746895, 0.76967419],
       [0.35896223, 0.36641998, 0.34013347, 0.90684176, 0.47245149],
       [0.38048223, 0.55069036, 0.51382272, 0.76348102, 0.81468832],
       [0.67733524, 0.76816219, 0.25850575, 0.71253371, 0.07651534],
       [0.60903466, 0.98130319, 0.02231213, 0.61559652, 0.15144025]])

In [420]:
arr.shape

(5, 5)

In [421]:
arr.max()

0.9813031908789496

In [422]:
arr.min()

0.022312130017606013

In [423]:
arr.argmax()

21

### Indexação e fatiamento 

In [424]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [425]:
arr[3]

3

In [426]:
arr[2:5] # final não inclusivo

array([2, 3, 4])

In [427]:
arr[:5]

array([0, 1, 2, 3, 4])

In [428]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [429]:
arr[2:18:4]

array([ 2,  6, 10, 14])

In [430]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [431]:
arr[-1]

29

In [432]:
arr[-1:]

array([29])

In [433]:
arr[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [434]:
arr[::-1] # inverte array

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [435]:
arr[-15:-1] = 100
arr


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100,  29])

In [436]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [437]:
arr = arr.reshape(5,10)


In [438]:
arr.shape

(5, 10)

In [439]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [440]:
arr[:][3:]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [441]:
arr[3][2]

32

In [442]:
arr2 = arr[:3] # arr2 aponta para o ary[:3], se modificar arr2 modifica arr
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [443]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [444]:
arr2[:] = 100

In [445]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [446]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [447]:
arr = np.arange(50).reshape(5,10)
arr
arr2 = arr[:3].copy()

In [448]:
arr2
arr2[0] = 100
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [449]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [450]:
arr[2,5]

25

In [451]:
arr[1:4, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [452]:
bol = arr > 20
bol

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [453]:
arr[bol]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [454]:
array = np.linspace(0,100,30)

In [455]:
array.shape

(30,)

In [456]:
array = array.reshape(3,10)

In [457]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [458]:
array[:2, 2]

array([ 6.89655172, 41.37931034])

### Operações com NumPy Arrays

In [459]:
arr = np.arange(16)

In [460]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [461]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [463]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [464]:
arr - arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [466]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [467]:
arr/arr # warning que causa um not a number

C:\Users\thass\AppData\Local\Temp\ipykernel_19928\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [469]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [470]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [471]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [472]:
np.mean(arr)

7.5