In [2]:
!pip install -q tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import matplotlib.pyplot as plt

In [3]:
setences = [
    "sequencia de texto inicial",
    "Gosto de sanduiche de milho",
    "Talvez eu compre um celta"
]


In [4]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE) #instancia de Tokenizer com 20000 palavras
tokenizer.fit_on_texts(setences) # aprende as sentenças
sequences = tokenizer.texts_to_sequences(setences)

In [5]:
print(sequences)

[[2, 1, 3, 4], [5, 1, 6, 1, 7], [8, 9, 10, 11, 12]]


In [6]:
tokenizer.word_index # elemento 0 é para padding

{'de': 1,
 'sequencia': 2,
 'texto': 3,
 'inicial': 4,
 'gosto': 5,
 'sanduiche': 6,
 'milho': 7,
 'talvez': 8,
 'eu': 9,
 'compre': 10,
 'um': 11,
 'celta': 12}

In [7]:
data = pad_sequences(sequences, maxlen=5)
print(data)

[[ 0  2  1  3  4]
 [ 5  1  6  1  7]
 [ 8  9 10 11 12]]


In [8]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[ 0  2  1  3  4]
 [ 5  1  6  1  7]
 [ 8  9 10 11 12]]


In [9]:
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post') # padding 0 ao final
print(data)

[[ 2  1  3  4  0]
 [ 5  1  6  1  7]
 [ 8  9 10 11 12]]


In [10]:
data = pad_sequences(sequences, maxlen=10) # muito padding
print(data)

[[ 0  0  0  0  0  0  2  1  3  4]
 [ 0  0  0  0  0  5  1  6  1  7]
 [ 0  0  0  0  0  8  9 10 11 12]]


In [11]:
data = pad_sequences(sequences, maxlen=3) # pouco padding trunca
print(data)

[[ 1  3  4]
 [ 6  1  7]
 [10 11 12]]


In [12]:
data = pad_sequences(sequences, maxlen=3, truncating='post') # pouco padding trunca
print(data)

[[ 2  1  3]
 [ 5  1  6]
 [ 8  9 10]]
